package com.selenide.tests.enums;

public enum Elements {

    WELCOME_PANEL,
    H1_PAGE_HEADER,

    LOGIN_FORM,
    LOGIN_USER_NAME,
    LOGIN_PASSWORD,
    LOGIN_REMEMBER_ME_CHECKBOX,
    LOGIN_BUTTON,

    PROFILE_LINK,

    PROFILE_LOCALE_SELECT,
    PROFILE_ADMIN_COLOR_SCHEME_FRESH,
    PROFILE_ADMIN_COLOR_SCHEME_LIGHT,
    PROFILE_ADMIN_COLOR_SCHEME_BLUE,
    PROFILE_ADMIN_COLOR_SCHEME_COFFEE,
    PROFILE_ADMIN_COLOR_SCHEME_ECTOPLASM,
    PROFILE_ADMIN_COLOR_SCHEME_MIDNIGHT,
    PROFILE_ADMIN_COLOR_SCHEME_OCEAN,
    PROFILE_ADMIN_COLOR_SCHEME_SUNRISE,

    PROFILE_UPDATE_BUTTON,
    PROFILE_UPDATE_MESSAGE

}
